# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-07 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import morango.models.fields.uuids


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0018_auto_20210714_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferSessionCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', morango.models.fields.uuids.UUIDField()),
                ('server_counter', models.IntegerField(default=0)),
                ('client_counter', models.IntegerField(default=0)),
                ('transfer_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsics', to='morango.TransferSession')),
            ],
        ),
        migrations.AddField(
            model_name='databasemaxcounter',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='transfersessioncounter',
            unique_together=set([('transfer_session', 'instance_id')]),
        ),
    ]
